services:
  sairam-mun-website:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10000:10000"
    environment:
      - NODE_ENV=production
      - PORT=10000
      - MONGODB_URI=mongodb+srv://sairamMUN:sairam2027@cluster0.uqjjz91.mongodb.net/sairamdb?retryWrites=true&w=majority

    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:10000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped 