services:
  - type: web
    name: sairam-mun-website
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://sairam-mun-website.onrender.com
      - key: RENDER_EXTERNAL_URL
        value: https://sairam-mun-website.onrender.com
    healthCheckPath: /api/health
    autoDeploy: true 